name: Build CV
on:
  push:
    branches: [github-actions] # TODO: Change to main
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: Jarivanbakel/typst-action@v3
        with:
          input_files: english.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: English PDF
          path: english.pdf
      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
